'''
Fibonacci series is one in which a new number is
generated by adding the previous two numbers.
Eg : 0 1 1 2 3 5 8 13 21 34 55 89
Algorithm for finding Fibonacci number less than a certain number n
Take base case f = 0 and l = 1. Then t = f + l is the new number.
Then replace the first number f = l and l = t. Perform this operation
recursively.
'''

# first is the first number, second is the second number and n is the upper limit
# of the series
def fibonacci(first, second, n):
    t = first + second
    if (t <= n):
        print(t)
        return fibonacci(second, t, n)
    else:
        return t

fibonacci(0, 1, 21)